### ISSUE TITLE
Throws errors to console

### ISSUE THREAD

**Issue by ebatgerel** [Borjagodoy/video-view#2]
Hi thanks for this component. When i use it it's throws some error ? 

`<video-view url="{{item.videoLink}}"></video-view>`

Here is a result:

![capture](https://user-images.githubusercontent.com/16677052/40097838-f9b3e0ce-590a-11e8-86df-9232d758fa39.PNG)

And console look like:

![capture](https://user-images.githubusercontent.com/16677052/40097868-1eec4188-590b-11e8-8447-d14631e594a1.PNG)

Is above errors just my link or ?

**Comment by Borjagodoy** [comment]
Can you test now? we hace a problem in a tag of the last version

**Comment by ebatgerel** [comment]
Its works now.
